version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords: ['typeas', 'arrayify', 'arrayable', 'boolify', 'floatify', 'integerify', 'integerable', 'unboolable', 'unfloatable', 'unintegerable', 'unstringable']
import: []
